#!/bin/bash
#This script produces a templayed report displaying system information.

cat << EOF

System Report generated by $USER on $currentDate

System Information
-------------------------
Hostname: 
OS: 
Uptime:

Hardware Information
-------------------------
CPU:
Speed: 
RAM: 
Disk(s):
Video:

Network Information
-------------------------
FQDN: 
Host Address:
Gateway IP:
DNS Server:

Interface Name:
IP Address:

System Status
-------------
Users Logged In:
Disk Space:
Process Count:
Load Averages:
Memory Allocation:
Listening Network Ports:
UFW Rules: 