#!/bin/bash
#This script produces a templayed report displaying system information.

#Find username and current date.

user=$(whoami)
currentDate=$(date)

#System Information section
#Find hostname, OS, and uptime.

hostname=$(hostname)
OS=$(hostnamectl | awk -F : '/Operating System:/ {print $2}')
uptime=$(uptime | awk '{print $3, substr($4,1, length($4)-1)}')

#Hardware Information Section
#Find CPU, speed, RAM, Disks, and video card
cpu=$(sudo lscpu | grep "Model name:" | awk ' { for (i=3; i<=NF; i++)   printf $i" " }')
speed=$(cat /proc/cpuinfo | awk '/MHz/ {print $4}' | head -n 1)
ramKB=$(cat /proc/meminfo | awk '/MemTotal/ {print $2}')
ramGB=$(($ramKB/1000000))
disks=$(sudo lsblk -o NAME,MODEL,SIZE -d | grep "sd")
videoCardMake=$(sudo lshw -numeric -C display | awk '/vendor/ { for (i=2; i<=NF; i++)   printf $i" " }')
videoCardModel=$(sudo lshw -numeric -C display | awk '/product/ { for (i=2; i<=NF; i++)   printf $i" " }')

#Network information section
#Find FQDN, Host address, Gateway IP, DNS Server, interface name, IP address
fqdn=$(hostname -A)
hostAddress=$(hostname -I)
defaultIP=$(ip route show | awk '/default/ {print $3}')
dnsIP=$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}')
intVendor=$(sudo lshw -class network | head | awk '/vendor/ { for (i=2; i<=NF; i++)   printf $i" " }')
intProduct=$(sudo lshw -class network | head | awk '/product/ { for (i=2; i<=NF; i++)   printf $i" " }')
#this line finds the interface that is connected to the default route
defaultInt=$(ip route show | awk '/default/ {print $5}')
#this line uses the name of the default interface to find the ip address of the primary interface
defaultIntIP=$(ip -br add show | grep $defaultInt | awk '{print $3}')

#System Status Section
#Find logged in Users, Disk Space, process count, load averages, memory allocation, listening ports, and firewall rules

currentUsers=$(who | awk '{print $1}')
diskSpace=$(df -h | awk '{print $6,'\t', '\t',  $4}')
numberOfProcesses=$(ps -e --no-headers | wc -l)
loadAverages=$(uptime | awk '{print $8, $9, $10}')
memAllocation=$(free -h)
ports=$(ss -tunlH | grep LISTEN | awk '{print $5}' | awk -F : '{print $NF}' | sort | uniq)
firewallRules=$(sudo ufw show added)

cat << EOF

System Report generated by $user on $currentDate

System Information
-------------------------
Hostname: $hostname
OS: $OS
Uptime: $uptime

Hardware Information
-------------------------
CPU: $cpu
Speed: $speed MHz
RAM: $ramGB GB
Disk(s):
$disks

Video: $videoCardMake $videoCardModel

Network Information
-------------------------
FQDN: $fqdn
Host Address: $hostAddress
Gateway IP: $defaultIP
DNS Server: $dnsIP

Interface Name: $intVendor $intProduct
IP Address: $defaultIntIP

System Status
-------------
Users Logged In: $currentUsers
Disk Space:
$diskSpace

Process Count: $numberOfProcesses
Load Averages: $loadAverages
Memory Allocation:
$memAllocation
Listening Network Ports:
$ports

UFW Rules: 
$firewallRules
EOF